test:
  image: python:3.11
  script:
    - pip install .
    - qeh graphene+doping=0.5 3BN --plasmons --save-plots "_g-3BN"

docs_test:
  image: python:3.11
  script:
    - pip install .[docs]
    - which sphinx-build
    - cd $CI_PROJECT_DIR/docs
    - make html
